# Generated by Django 3.1.7 on 2021-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='openforscoring',
            field=models.BooleanField(default=False),
        ),
    ]
