# Generated by Django 3.1.7 on 2021-03-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup', '0002_week_openforscoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='maxpoints',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
