# Generated by Django 3.1.7 on 2021-03-30 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup', '0003_week_maxpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='weeknummer',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
