# Generated by Django 3.1.7 on 2021-03-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup', '0006_scores_finalscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='finalscore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
