# Generated by Django 3.1.7 on 2021-04-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup', '0007_auto_20210330_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='baan',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='scores',
            name='lus',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
